### Base Learner 8  - Load Fit10 Model

In [2]:
from fastai2.vision.all import *
import sys, torch
sys.path.append('..')

torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False


# %load_ext autoreload
# %autoreload 2
from modules.learnutils import TestSetRecorder
from modules.expbuilder import default_params, run_exp, rm_test_recorder

train_path = Path('../../../rf-chess-data/cropped_v1/')
train_clean_path = Path('../../../rf-chess-data/cropped_v1.1/')

test_path_all = Path('../../../other-chess-data/regulation-test-2-all/')
test_path_easy = Path('../../../other-chess-data/regulation-test-2-easy/')

In [3]:
learn = load_learner('../models/base-learner7-fit10.pkl')
learn.path = Path('../../../rf-chess-data/cropped_v1.1')

my_params = {'_train_seed':0, '_custom_crop': 'my-top-crop', 
             '_model_arch': resnet50,
            '_train_path':train_clean_path,
            '_learn_norm': False,
            }
default_params.update(my_params)
set_seed(42)

train_dl, learn_fresh = run_exp(default_params, 'dummy', b_ret=True,)

# learn.cbs.pop(3)

learn.dls = learn_fresh.dls

learn.add_cb(TestSetRecorder())

##### 0

In [4]:
set_seed(0)
learn.fine_tune(20)

In [5]:
pd.DataFrame(learn.cbs[3].values)

           0         1         2         3
0   1.642789  0.500000  0.929825  0.557018
1   1.427014  0.627193  0.916667  0.710526
2   1.135178  0.675439  0.951754  0.719298
3   1.033293  0.692982  0.960526  0.750000
4   1.036367  0.706140  0.969298  0.758772
5   0.925820  0.736842  0.973684  0.780702
6   0.924357  0.732456  0.960526  0.776316
7   0.836314  0.741228  0.973684  0.780702
8   0.866296  0.732456  0.969298  0.776316
9   0.846266  0.741228  0.969298  0.789474
10  0.846266  0.741228  0.969298  0.789474
11  1.043354  0.666667  0.956140  0.728070
12  0.838691  0.736842  0.951754  0.802632
13  0.812612  0.763158  0.951754  0.802632
14  0.763413  0.785088  0.973684  0.824561
15  1.201411  0.719298  0.960526  0.780702
16  0.824045  0.776316  0.960526  0.837719
17  0.655332  0.789474  0.978070  0.855263
18  0.534827  0.833333  0.982456  0.859649
19  0.619070  0.842105  0.986842  0.872807
20  0.518962  0.850877  0.986842  0.868421
21  0.638775  0.824561  0.995614  0.837719
22  0.536827  0.850877  0.978070  0.894737
23  0.581069  0.850877  0.982456  0.881579
24  0.697252  0.815789  0.986842  0.850877
25  0.376048  0.872807  0.982456  0.894737
26  0.430049  0.872807  0.982456  0.899123
27  0.419959  0.872807  0.982456  0.894737
28  0.397870  0.881579  0.991228  0.899123
29  0.364227  0.877193  0.991228  0.894737
30  0.381605  0.881579  0.982456  0.894737
31  0.372564  0.881579  0.986842  0.894737

##### 1

In [6]:
learn = load_learner('../models/base-learner7-fit10.pkl')
learn.path = Path('../../../rf-chess-data/cropped_v1.1')

my_params = {'_train_seed':0, '_custom_crop': 'my-top-crop', 
             '_model_arch': resnet50,
            '_train_path':train_clean_path,
            '_learn_norm': False,
            }
default_params.update(my_params)
set_seed(42)

train_dl, learn_fresh = run_exp(default_params, 'dummy', b_ret=True,)

# learn.cbs.pop(3)

learn.dls = learn_fresh.dls

learn.add_cb(TestSetRecorder())

In [7]:
set_seed(1)
learn.fine_tune(20)

In [8]:
pd.DataFrame(learn.cbs[3].values)

           0         1         2         3
0   1.642789  0.500000  0.929825  0.557018
1   1.427014  0.627193  0.916667  0.710526
2   1.135178  0.675439  0.951754  0.719298
3   1.033293  0.692982  0.960526  0.750000
4   1.036367  0.706140  0.969298  0.758772
5   0.925820  0.736842  0.973684  0.780702
6   0.924357  0.732456  0.960526  0.776316
7   0.836314  0.741228  0.973684  0.780702
8   0.866296  0.732456  0.969298  0.776316
9   0.846266  0.741228  0.969298  0.789474
10  0.846266  0.741228  0.969298  0.789474
11  1.291273  0.671053  0.934211  0.745614
12  0.854660  0.750000  0.960526  0.798246
13  0.904393  0.750000  0.964912  0.780702
14  0.714879  0.802632  0.964912  0.824561
15  0.684673  0.807018  0.973684  0.833333
16  0.685717  0.802632  0.982456  0.815789
17  0.488124  0.833333  0.982456  0.855263
18  0.746390  0.793860  0.986842  0.820175
19  0.487980  0.833333  0.982456  0.864035
20  0.491578  0.828947  0.982456  0.859649
21  0.682189  0.824561  0.982456  0.842105
22  0.837516  0.758772  0.969298  0.785088
23  0.395025  0.864035  0.956140  0.894737
24  0.502091  0.850877  0.973684  0.855263
25  0.404975  0.890351  0.991228  0.907895
26  0.408051  0.868421  0.960526  0.894737
27  0.357297  0.881579  0.956140  0.916667
28  0.366215  0.890351  0.973684  0.912281
29  0.362156  0.877193  0.964912  0.894737
30  0.367787  0.890351  0.978070  0.894737
31  0.360821  0.881579  0.960526  0.903509

##### 2

In [9]:
learn = load_learner('../models/base-learner7-fit10.pkl')
learn.path = Path('../../../rf-chess-data/cropped_v1.1')

my_params = {'_train_seed':0, '_custom_crop': 'my-top-crop', 
             '_model_arch': resnet50,
            '_train_path':train_clean_path,
            '_learn_norm': False,
            }
default_params.update(my_params)
set_seed(42)

train_dl, learn_fresh = run_exp(default_params, 'dummy', b_ret=True,)

# learn.cbs.pop(3)

learn.dls = learn_fresh.dls

learn.add_cb(TestSetRecorder())

In [10]:
set_seed(2)
learn.fine_tune(20)

In [11]:
pd.DataFrame(learn.cbs[3].values)

           0         1         2         3
0   1.642789  0.500000  0.929825  0.557018
1   1.427014  0.627193  0.916667  0.710526
2   1.135178  0.675439  0.951754  0.719298
3   1.033293  0.692982  0.960526  0.750000
4   1.036367  0.706140  0.969298  0.758772
5   0.925820  0.736842  0.973684  0.780702
6   0.924357  0.732456  0.960526  0.776316
7   0.836314  0.741228  0.973684  0.780702
8   0.866296  0.732456  0.969298  0.776316
9   0.846266  0.741228  0.969298  0.789474
10  0.846266  0.741228  0.969298  0.789474
11  1.033055  0.710526  0.960526  0.763158
12  0.816813  0.758772  0.964912  0.811404
13  0.788350  0.771930  0.960526  0.802632
14  0.834908  0.758772  0.973684  0.802632
15  0.717296  0.771930  0.973684  0.833333
16  0.773150  0.767544  0.991228  0.789474
17  0.717839  0.789474  0.978070  0.815789
18  0.792640  0.785088  0.969298  0.798246
19  0.571354  0.837719  0.991228  0.855263
20  0.611160  0.811404  0.964912  0.846491
21  0.460763  0.837719  0.991228  0.842105
22  0.488652  0.833333  0.986842  0.850877
23  0.588966  0.811404  0.986842  0.828947
24  0.428727  0.868421  0.995614  0.877193
25  0.439932  0.855263  0.986842  0.864035
26  0.512400  0.833333  0.986842  0.850877
27  0.417730  0.885965  0.986842  0.903509
28  0.403181  0.881579  0.991228  0.899123
29  0.416828  0.881579  0.978070  0.903509
30  0.437263  0.877193  0.991228  0.881579
31  0.430185  0.877193  0.986842  0.885965

In [12]:
learn.fine_tune(10)

In [15]:
pd.DataFrame(learn.cbs[3].values).iloc[-6:,:]

           0         1         2         3
37  0.365990  0.881579  0.986842  0.903509
38  0.413174  0.837719  0.947368  0.890351
39  0.475002  0.850877  0.986842  0.864035
40  0.485366  0.824561  0.995614  0.842105
41  0.389884  0.877193  0.986842  0.890351
42  0.392109  0.877193  0.986842  0.890351

In [17]:
from modules.trainutils import my_test_metrics

In [20]:
my_test_metrics(learn, test_path_all)

(0.39210907304496095, 0.8771929824561403)